# Blocky DNS Server Configuration
# Blocks gambling websites using custom blocklist

# Upstream DNS servers (where to forward allowed queries)
upstream:
  default:
    - 1.1.1.1  # Cloudflare
    - 8.8.8.8  # Google DNS

# Blocklist configuration
blocking:
  # CUSTOM BLOCKLIST - Maintained in this repo!
  blackLists:
    gambling:
      # YOUR custom gambling blocklist (edit gambling-blocklist.txt)
      - https://raw.githubusercontent.com/dwhale000/checkpoint-dns-server/main/gambling-blocklist.txt

      # TO UPDATE:
      # 1. Edit gambling-blocklist.txt locally
      # 2. git commit -am "Updated blocklist"
      # 3. git push
      # 4. flyctl deploy (or wait 4 hours for auto-refresh)

  # Apply gambling blocklist to ALL clients
  clientGroupsBlock:
    default:
      - gambling

  # What to return for blocked domains
  blockType: zeroIp  # Returns 0.0.0.0 for IPv4, :: for IPv6

  # Enable blocking
  loading:
    downloads:
      timeout: 60s
      attempts: 5
      cooldown: 10s

  # How often to refresh the blocklist
  refreshPeriod: 4h

# Ports configuration
ports:
  dns: 53      # Standard DNS port
  http: 8080   # HTTP port for DoH
  https: 443   # HTTPS port for DoH (DNS-over-HTTPS)

# Logging
log:
  level: info
  format: text
  timestamp: true

# Enable query logging - shows BLOCKED queries
queryLog:
  type: console
  target: stdout
  logRetentionDays: 0
  fields:
    - clientIP
    - clientName
    - responseReason
    - responseAnswer
    - question
    - duration

# Enable prometheus metrics (optional)
prometheus:
  enable: false

# Bootstrap DNS (used to resolve blocklist URLs)
bootstrapDns: tcp+udp:1.1.1.1
